# Usa un'immagine base di Python
FROM python:3.10

# Imposta la directory di lavoro
WORKDIR /app/src/main/python

# Copia il resto del codice sorgente
COPY . /app

ENV PYTHONPATH /app/src/main/python:$PYTHONPATH

# Copia i file di requisiti
COPY requirements.txt .

# 4. Installa le dipendenze
RUN pip install --no-cache-dir -r requirements.txt

# Esegui il tuo programma
# CMD ["python3 /app/src/main/python/Core/Starter.py"] Esegui questo comando una volta nel container di docker in modo da avviare il tool
# Se docker non funziona esegui il cmd da amministratore e scrivi questo: bcdedit /set hypervisorlaunchtype on