version: "3.7"

services:
  dpdpython:
    image: dpdpython
    restart: always
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  backend-gunicorn:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      args:
        - version=${BACKEND_PYTHON_VERSION}
    restart: always
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - BACKEND_URL=${BACKEND_URL}
    ports:
      - "${BACKEND_PORT}:${BACKEND_DEFAULT_PORT}"
    volumes:
      - ./backend/code:/app
      - /app/node_modules
    command: >
      sh -c "gunicorn --bind :${BACKEND_PORT} backend.wsgi"
    depends_on:
      - db
  backend-apache:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      args:
        - version=${BACKEND_PYTHON_VERSION}
    restart: always
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - BACKEND_URL=${BACKEND_URL}
    ports:
      - "${BACKEND_PORT_APACHE}:${BACKEND_DEFAULT_PORT_APACHE}"
    volumes:
      - ./backend/code:/app
      - /app/node_modules
    command: >
        sh -c "mod_wsgi-express start-server backend/wsgi.py --user www-data --group www-data --port ${BACKEND_PORT_APACHE}"
    depends_on:
      - db
#gunicorn --bind 0.0.0.0:5000 manage:app
#python manage.py makemigrations backend && python manage.py migrate && python manage.py runserver 0:${BACKEND_DEFAULT_PORT} 
#gunicorn --bind :8000 --workers 3 --threads 2 project.wsgi:application
#mod_wsgi-express start-server /code/backend/wsgi.py --user www-data --group www-data --port 8010